config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'
  get '/portfolio' => 'pages#portfolio'
  get '/about' => "pages#about"
  get '/contact' => 'pages#contact'
  get '/resume' => 'pages#resume'
  get '/analytics' => 'pages#analytics'
  get '/moderation' => 'pages#moderation'
  get '/trigger' => 'pages#trigger'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome

  end

  def portfolio

  end

  def resume

  end

  def about

  end

  def contact

  end

  def analytics

  end

  def moderation

  end

  def trigger

  end
end

app/helpers/application_helper.rb
require 'pry'
module ApplicationHelper
  def is_active(action)       
    params[:action] == action ? "active" : nil        
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

</head>
<body>
  <div class="header">
    <ul>
      <li class="<%=is_active('welcome')%>"><%= link_to "Welcome", root_path %></li>
      <li class="<%=is_active('about')%>"><%= link_to "About", about_path %></li>
      <li class="<%=is_active('portfolio')%>"><%= link_to "Portfolio", portfolio_path %></li>
      <li class="<%=is_active('resume')%>"><%= link_to "Resume", resume_path %></li>
    </ul>
  </div>

  <div class="content">
    <%= yield %>
  </div>

  <div class="footer">

    <a href="https://github.com/lovedoodle"><i class="fa fa-github-alt footerFa"></i></a>
    <a href='https://www.linkedin.com/in/jingwait'><i class="fa fa-linkedin footerFa"></i></a>
    <a href='https://twitter.com/JingWait'><i class="fa fa-twitter footerFa"></i></a>

  </div>
</body>
</html>

app/views/pages/about.html.erb
<div class="mainContent aboutPage">
  <div class="aboutImg">
    <img src="assets/about/images/about_resized.jpg" alt="" />
  </div>
  <div class="aboutText">
      <p>
        I came to America from China in 2012 and have been living in PDX since March 2014. My American dream is working full time as a software engineer and being good at it.
      </p>

      <p>
        I became interestd in Web Development in 2015. I love Web Development because it gives me a creative outlet and also allows me to create something useful for people too. I get to learn something new everyday. I love the feeling that comes from using various web apps and gradually knowing more and more about how they're made and the technologies they use.
      </p>

      <p>
        After graduating from Epicodus's Ruby/JavaScript class, I have been interning at Chirpify. At first I was only responsible for small bug fixes and additions. Since July I've been responsible for the majority of all frontend code and design. Check out some of my work <a href="/portfolio">here</a>.
      </p>

      <p>
        In China I worked as a Recruitor and Office Assistant for multi-national corporations. I was on teams that included people from Mainland China, Hong Kong, Southeast Asia, India, and Germany. I know what it's like to work with people from many different backgrounds and I love to be a team player, enabling others to succeed alongside myself.
      </p>
  </div>

</div>

app/views/pages/analytics.html.erb
<div class="mainContent">
  <div class="internIntro">
    <h2>Analytics Dashboard</h2>
    <div class="internImg">
      <a href="portfolio/analyticImg.png" target="_blank"><img src="portfolio/analyticImg.png"  alt="" /></a>
    </div>
    <p>
      When starting the redesign of the Analytics dashboard, I was told to do the layout using CSS Flexbox. I had never used that before and I was nervous. After reading Angular Material's documentation and some experimentation I was able to get a handle on it. It was my first time "learning on the job". I found the supportive office environment and the encouragement from my co workers lead to me learning something much faster than when I was home studying alone.
      <br/>
      <br/>
      Other colleagues of mine did the actual analytic calculations and I worked with them to incorporate the design and functionality of the javascript frontend with the ruby backend. It was quite an experience and one I would love to experience all the time!
    </p>

  </div>

</div>

app/views/pages/moderation.html.erb
<div class="mainContent">
  <div class="internIntro">
    <h3>Moderation Quene</h3>
    <p>
      This project was quite a challenge! The feature existed in a rudimentary form before I began. I was given a few images with the desired design and a few UI elements. I was able to take some creative license with how I designed the filters UI element since that wasn't explicitly designed.
      <br/>
      <br/>
      I really enjoyed this project. It was fun to take the old page and transform it into much more usable and beautiful page. It's now ready for Chirpify's clients to start using!
    </p>
    <div class="internImg">
      <img src="portfolio/mod_q_2.png" alt="" />

    </div>
    <div class="internImg">
      <img src="portfolio/mod_q_3.png" alt="" />
    </div>
  </div>  

</div>

app/views/pages/portfolio.html.erb
<div class="mainContent">
  <!-- <div class="row"> -->
  <div class="projectDiv">
    <%= link_to(analytics_path) do %>
      <div class="projectsImg">
        <img src="portfolio/analyticImg.png" alt="" />
      </div>
      <div class="projectsText">
        <h3>Analytics</h3>
        <p>
          A design refresh of a consumer facing product I completed as my first feature task for Chirpify.
        </p>
      </div>
    <% end %>
  </div>

  <div class="projectDiv">
    <%= link_to(moderation_path) do %>
      <div class="projectsImg">
        <img src="portfolio/mod_q_2.png" alt="" />
      </div>
      <div class="projectsText">

        <h3>Moderation Quene</h3>
        <p>
          New features along with a complete app redesign I completed for Chirpify.
        </p>
      </div>
    <% end %>
  </div>


  <div class="projectDiv">
    <%= link_to(trigger_path) do %>
      <div class="projectsImg">
        <img src="portfolio/follow_1.png" alt="" />
      </div>
      <div class="projectsText">

        <h3>Trigger Create</h3>
        <p>
          Complete rewrite and redesign of two feature creation UI elements along with some new features like meta field editing.
        </p>
      </div>
    <% end %>
  </div>

  <div class="projectDiv">
    <a href="https://angularpizzaplanet.herokuapp.com">
      <div class="projectsImg">
        <img src="portfolio/pizza.png" alt="" />
      </div>
      <div class="projectsText">

        <h3>Pizza Planet</h3>
        <p>
          A pet project I did with Yeoman/Angular practicing two-way data binding, custom directives, and inline editing.
        </p>
      </div>
    </a>

  </div>

  <div class="projectDiv">
    <a href="https://twittersearchmap.herokuapp.com/#/">
      <div class="projectsImg">
        <img src="portfolio/twittersearch.png" alt="" />
      </div>
      <div class="projectsText">

        <h3>Twitter Search</h3>
        <p>
          An Angular and Express project that allows a user to search via keyword for related tweets in PDX and show tweets on Google map.
        </p>
      </div>
    </a>

  </div>


</div>

app/views/pages/resume.html.erb
<div class="mainContent resumeWrap">

	<div class="resumeHeader">
		<h3>Jing Wait</h3>
		<ul id="printResumeContact">
			<!-- <li>https://jingwait.herokuapp.com/</li> -->
			<li><a href="github.com/lovedoodle">github.com/lovedoodle</a></li>
			<li>jingzhaowait@gmail.com</li>
			<li>1-541-636-7552</li>
		</ul>
		<ul id="resumeContact">
			<!-- <li><a href="https://jingwait.herokuapp.com/">Portifolio</a></li> -->
			<li><a href="https://github.com/lovedoodle">github.com/lovedoodle</a></li>
			<li><a href="mailto:jingzhaowait@gmail.com">jingzhaowait@gmail.com</a></li>
			<li>541-636-7552</li>
		</ul>
	</div>

	<div class="resumeIntro">
		<h3 class="section">About Myself</h3>
		<p>
			I keep great design and user experiences in mind while writing code. I love being a developer because I go into work everyday excited to work with a team of professional creatives and engineers. I'd love to be part of a new team writing great software.
		</p>
	</div>

	<div class="resumeSkills">
		<h3 class="section">Skills</h3>
		<em>Proficient:</em>
		<ul>
			<li>React</li>
			<li>AngularJS/Angular Material</li>
			<li>Javascript/ES6/ES7</li>
			<li>Ruby</li>
			<li>Sinatra</li>
			<li>MySQL</li>
			<li>Git</li>
			<li>HTML/CSS/SCSS</li>
		</ul>

		<em>Experienced with:</em>
		<ul>
			<li>
				NodeJS/Yarn/Webpack
			</li>
			<li>Sidekiq</li>
			<li>
				Heroku
			</li>
			<li>
				MongoDB
			</li>
		</ul>

	</div>

	<div class="resumeExperiences">
		<h3 class="section">Experiences</h3>
		<div class="">
			<p class="company">Front End Developer at Chirpify (June, 2016 - Present)</p>
			<ul>
				<li>Build UI component for Chirpify latest projects with React & NodeJS stack</li>
				<li>
					Responsible for redesign and implementation of <a href="//points.marriottrewards.com">points.marriottrewards.com</a>
				</li>
				<li>
					Go-to developer for client frontend design and feature requests
				</li>
				<li>Responsible for most new features on Chirpify's public and internal sites.</li>
			 	<!-- <li>Implementing designs using flex layout and Angular Material.</li> -->
				<li>Write AngularJS modules/apps and converting old pages to SPA style pages alongside a legacy Sinatra app.</li>
				<li>Experienced in writing RESTful API endpoints to support custom integrations</li>
				<li>Write and Run Custom Scripts for Client Requests, e.g. Campaign Performance Stats</li>
			</ul>
		</div>
		<div class="">
			<p class="company">Ruby/Javascript Student at Epicodus (Aug - Dec, 2015)</p>
			<ul>
				<li>Pair programming building database driven Sinatra/Rails/Ember apps</li>
			 	<li>Group projects including TwitterBot/Daycare Share </li>
			 	<li>Pawsome dog boarding app with rails and Google Map api </li>
			</ul>
		</div>
		<div class="">
			<p class="company">HR Specialist at Sirona/Philips/OnReal (Jun, 2009 - Jul, 2012)</p>
			<ul>
				<li>Maintained personnel files while conforming to regulations and auditing procedures</li>
			 	<li>Recruited new hires and answered questions regarding company culture, policy, and benefits</li>
	      <li>Found sources for office equipment, appreciation parties, hotels reservations, and air tickets</li>
			</ul>
		</div>
	</div>

	<div class="">
		<h3 class="section">Education</h3>
		<p>
			Epicodus, Web Development with Emphasis on Javascript and Ruby
		</p>
		<p>
			Xi'an University, B.S. in Political Science
		</p>
	</div>
</div>

app/views/pages/trigger.html.erb
<div class="mainContent">
  <div class="internIntro">
    <h3>Follow and Location Trigger Redesign</h3>
    <p>
      After finishing a couple projects there was a lull so I went looking for parts of the platform I could improve. I saw the Follow and Location trigger page wasn't very well designed in its beta state, so I took upon myself to write a list of improvements to be made. I took this list to the team and asked if I could take this on as a project. They said yes so I got to work.
      <br/>
      <br/>
      The first version of the project consisted mostly of text inputs next to each other. I thought an organized table design might make it easier to read and edit many different entries at the same time. I took full advantage of the Angular Material library, including the form controls, form validation for the Save button and its modal dialog features. The save buttons only are enabled when real changes have been made making it seem very professional and polished.
    </p>
    <div class="internImg">
      <img src="portfolio/follow_1.png" alt="" />
    </div>
    <div class="internImg">
      <img src="portfolio/follow_2.png" alt="" />
    </div>
    <div class="internImg">
      <img src="portfolio/follow_3.png" alt="" />
    </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<div class="welcomeJumbo">
  <div class="mainContent">
    <div class="welcomeBanner">
      <h1>Hello & Welcome</h1>
      <h1>My name is Jing Wait</h1>
      <!-- <h1>I love writing code and building beautiful sites</h1> -->
      <h1>I love building beautiful websites and writing code</h1>
      <span id='viewWorks'><%= link_to 'View My Work', portfolio_path %></span>
    </div>

  </div>


</div>